### ISSUE TITLE
Missing PDF file

### ISSUE THREAD

**Issue by iciocoiu** [Beciu/Subiecte-BAC-2009#1]
Salut,
@Beciu ai cumva salvat fișierul PDF cu enunțurile undeva si îl poți urca pe git? Pare ca [link-ul acela](https://profs.info.uaic.ro/cosmin.varlan/pagini/resurse_pregatire/variante-bac-2009-informatica-intensiv.pdf) nu mai exista.

**Comment by Beciu** [comment]
Hello,
Am updatat linkul cu PDF-ul. Acum l-am pus in cloud pe MEGA. Ar trebui sa functioneze.

**Comment by iciocoiu** [comment]
fixed in 391a98208b424d9b9380ee55a2bca79076a08ada
