### ISSUE TITLE
Add solution files for VAR 1,2,3

### ISSUE THREAD

**Issue by iciocoiu** [Beciu/Subiecte-BAC-2009#2]
salut @Beciu,
Poti sa adaugi si restul de rezolvări pentru variantele 1, 2 si 3? (poza/scan sau cod sursa)

Exercitiul 1 si Exercițiul 2 (cu punctele a,b,c si d).

**Comment by Beciu** [comment]
Da, le voi incarca in scurt timp. Totodata, @iciocoiu, nu as putea sa le pun si pe restul? Sunt deja scrise in caiet...

**Comment by iciocoiu** [comment]
desigur, am deschis acest issue pentru VAR 1,2,3 pentru început ca sa nu fie prea mult de lucru dar le poți adăuga pe toate, normal 👍 
PS: poti inchide tu issue cu "Close issue as completed" cand consideri ca este complet.
