### ISSUE TITLE
Validate solution for Pascal matches C++

### ISSUE THREAD

**Issue by iciocoiu** [Beciu/Subiecte-BAC-2009#4]
@Beciu poti sa validezi ca [fisierul cu rezolvari Pascal](https://github.com/Beciu/Subiecte-BAC-2009/blob/main/rezolvari_S1_bac_2009.pdf) adaugat se potriveste si pentru variantele de la C++?

Pare ca fisierul adaugat este de la variantele cu limbajul Pascal (nu am idee daca sunt aceleasi enunturi si difera doar limbajul de programare Pascal vs C++) sau sunt enunturi si rezolvari diferinte.

**Comment by Beciu** [comment]
Cum am spus si astazi, da, este un document de incredere.
